"""도구 검색용 별칭(동의어, 약어, 일상 표현).

도구 설명은 법령 용어(양도소득세, 종합부동산세)를 쓰지만 사용자는 줄임말과 일상 표현(양도세,
종부세, 집 팔 때 세금)으로 찾는다. ``sootool.search`` 의 점수 계산이 이 표를 함께 본다. 이름과
설명에 이미 있는 단어는 적지 않는다. 도구 이름이 바뀌면 ``tests/core/test_catalog_aliases.py`` 가
존재하지 않는 도구를 가리키는 항목을 잡아낸다.

작성자: 최진호
작성일: 2026-10-03
"""
from __future__ import annotations

from typing import Final

ALIASES: Final[dict[str, tuple[str, ...]]] = {
    # 세금
    "tax.capital_gains_kr":              ("양도세", "집 팔 때 세금", "장기보유특별공제", "capital gains tax korea"),
    "realestate.kr_transfer_tax":        ("양도세", "부동산 양도세", "집 팔 때 세금", "주택 양도"),
    "realestate.kr_acquisition_tax":     ("취득세", "집 살 때 세금", "주택 구입 세금", "등기"),
    "realestate.kr_comprehensive":       ("종부세", "보유세", "종합부동산세"),
    "realestate.kr_property_tax":        ("재산세", "보유세", "공시가격", "공시가액"),
    "realestate.kr_local_property":      ("지자체 세율", "서울 경기 세율", "탄력세율"),
    "realestate.kr_ltv":                 ("담보인정비율", "대출 한도", "주택담보대출"),
    "realestate.kr_dti":                 ("총부채상환비율", "대출 한도", "대출 규제"),
    "realestate.kr_dsr":                 ("총부채원리금상환비율", "대출 한도", "대출 규제"),
    "realestate.rental_yield":           ("월세 수익률", "임대 수익", "수익형 부동산"),
    "tax.kr_income":                     ("소득세", "종합소득세", "근로소득세", "종소세", "income tax korea"),
    "tax.kr_corporate":                  ("법인세", "법인 세금", "corporate tax korea"),
    "tax.kr_gift":                       ("증여", "증여세", "자녀에게 증여", "gift tax"),
    "tax.kr_inheritance":                ("상속", "상속세", "유산", "inheritance tax"),
    "tax.kr_simplified_vat":             ("간이과세", "부가세", "부가가치세", "소규모 사업자 부가세"),
    "tax.kr_local_income_tax":           ("지방소득세", "주민세", "소득세의 10%"),
    "tax.kr_education_tax_add":          ("지방교육세", "교육세"),
    "tax.kr_rural_special_tax":          ("농특세", "농어촌특별세", "농특세 20%"),
    "tax.kr_withholding_simple":         ("원천징수", "간이세액표", "월급 원천징수", "withholding"),
    "tax.progressive":                   ("누진세", "세율 구간", "bracket", "progressive tax"),
    "tax_us.federal_income":             ("미국 소득세", "IRS", "us income tax", "federal tax"),
    "tax_us.capital_gains":              ("미국 양도세", "미국 주식 양도", "us capital gains"),
    "tax_us.state_tax":                  ("미국 주세", "캘리포니아", "뉴욕", "텍사스", "state income tax"),
    # 급여
    "payroll.kr_salary":                 ("실수령액", "월급 실수령", "연봉 실수령", "세후 월급", "4대보험", "net salary", "take-home pay"),
    "payroll.hourly_to_monthly_net":     ("시급", "알바", "아르바이트", "시급 월급 환산", "hourly wage"),
    "payroll.kr_severance_pay":          ("퇴직금", "퇴직소득세", "퇴직할 때 세금", "severance"),
    "payroll.kr_year_end_tax_settlement":("연말정산", "환급", "13월의 월급", "공제 합산"),
    "payroll.kr_bonus_tax":              ("상여", "보너스", "성과급", "상여금 세금", "bonus tax"),
    "payroll.kr_medical_deduction":      ("의료비", "병원비 공제", "난임"),
    "payroll.kr_education_deduction":    ("교육비", "학원비 공제", "자녀 교육비"),
    "payroll.kr_donation_deduction":     ("기부금", "기부 공제", "donation"),
    "payroll.kr_housing_loan_deduction": ("주택담보 이자", "대출 이자 공제", "장기주택저당차입금"),
    # 회계
    "accounting.vat_add":                ("부가세", "부가가치세", "VAT", "공급가액", "세금 더하기"),
    "accounting.vat_extract":            ("부가세 역산", "VAT 분리", "공급가액 구하기", "세금 빼기", "부가세 포함 금액"),
    "accounting.depreciation_straight_line": ("감가상각", "정액법", "depreciation"),
    "accounting.depreciation_declining_balance": ("감가상각", "정률법"),
    "accounting.depreciation_units_of_production": ("감가상각", "생산량 비례"),
    "accounting.balance":                ("대차 균형", "차변 대변", "분개 검증", "trial balance"),
    "accounting.ratios":                 ("재무비율", "부채비율", "유동비율", "financial ratios"),
    "accounting.income_statement":       ("손익계산서", "영업이익", "income statement", "P&L"),
    "accounting.break_even":             ("손익분기점", "BEP", "공헌이익", "break-even sales volume"),
    "accounting.cashflow_operating":     ("현금흐름", "영업활동", "CFO", "cash flow"),
    # 금융
    "finance.loan_schedule":             ("대출 상환", "이자 계산", "원리금균등", "원금균등", "할부", "amortization", "mortgage", "loan"),
    "finance.pv":                        ("현재가치", "할인", "discount"),
    "finance.fv":                        ("미래가치", "복리", "compound interest", "적금", "예금 만기"),
    "finance.npv":                       ("순현재가치", "투자 타당성", "현금흐름 할인"),
    "finance.irr":                       ("내부수익률", "투자 수익률", "internal rate of return"),
    "finance.roi":                       ("투자수익률", "투자 대비 수익", "return on investment"),
    "finance.cagr":                      ("연평균 성장률", "복합연평균성장률", "CAGR", "compound annual growth rate"),
    "finance.payback_period":            ("투자 회수 기간", "자본 회수 기간", "payback"),
    "finance.bond_ytm":                  ("채권 수익률", "만기수익률", "yield to maturity"),
    "finance.black_scholes":             ("옵션 가격", "블랙숄즈", "option pricing"),
    "finance.var_historical":            ("위험가치", "손실 한도", "value at risk"),
    "finance.sharpe_ratio":              ("샤프지수", "위험조정수익률"),
    # 날짜
    "datetime.age":                      ("만 나이", "만나이", "나이 계산", "생일", "법정 나이", "age"),
    "datetime.add_business_days":        ("영업일 더하기", "근무일 계산", "휴일 제외", "business days"),
    "datetime.count_business_days":      ("영업일 수", "근무일 수", "공휴일 제외 일수"),
    "datetime.diff":                     ("날짜 차이", "며칠 남았", "D-day", "기간 계산", "date difference"),
    "datetime.day_count":                ("이자 일수", "일수 계산", "30/360", "ACT/365"),
    "datetime.lunar_to_solar":           ("음력 양력 변환", "음력 생일", "lunar calendar"),
    "datetime.solar_to_lunar":           ("양력 음력 변환", "음력 날짜"),
    "datetime.lunar_holiday":            ("설날", "추석", "명절", "대보름", "초파일"),
    "datetime.solar_terms":              ("절기", "입춘", "동지", "24절기"),
    "datetime.tz_convert":               ("시차", "시간대 변환", "timezone"),
    "datetime.tax_period_kr":            ("과세기간", "과세 기간 판정"),
    "datetime.payroll_period":           ("급여 주기", "월급일 기준 기간"),
    # 단위
    "units.fx_convert":                  ("환율", "환전", "달러 원화", "currency exchange"),
    "units.fx_triangulate":              ("삼각 환율", "교차 환율", "cross rate"),
    "units.temperature":                 ("섭씨", "화씨", "온도 변환"),
    "units.convert":                     ("단위 변환", "unit conversion"),
    # 의료
    "medical.bmi":                       ("비만도", "체질량지수", "body mass index"),
    "medical.bsa":                       ("체표면적", "body surface area"),
    "medical.egfr":                      ("신장 기능", "사구체 여과율", "kidney function"),
    "medical.pregnancy_weeks":           ("임신 주수", "출산 예정일", "due date"),
    # 통계
    "stats.ttest_two_sample":            ("t 검정", "두 집단 비교", "평균 차이 검정"),
    "stats.ttest_one_sample":            ("t 검정", "표본 평균 검정"),
    "stats.ttest_paired":                ("대응표본", "전후 비교", "paired t-test"),
    "stats.anova_oneway":                ("분산분석", "세 집단 이상 비교", "ANOVA"),
    "stats.regression_linear":           ("회귀분석", "선형회귀", "추세선", "linear regression"),
    "stats.descriptive":                 ("기술통계", "평균 표준편차", "summary statistics"),
    "stats.ci_mean":                     ("신뢰구간", "confidence interval"),
    "stats.chi_square_independence":     ("카이제곱", "독립성 검정", "교차표"),
    "stats.mann_whitney_u":              ("비모수 검정", "만휘트니"),
    "stats.bootstrap_ci":                ("부트스트랩", "재표본"),
    # 프로젝트 관리와 계산
    "pm.critical_path":                  ("주공정", "크리티컬 패스", "CPM", "일정 계획"),
    "pm.evm":                            ("획득가치", "EVM", "비용 성과", "일정 성과"),
    "pm.pert":                           ("PERT", "낙관 비관 추정", "일정 추정"),
    "pm.monte_carlo_schedule":           ("몬테카를로", "일정 불확실성", "완료 확률"),
    "core.calc":                         ("수식 계산", "계산기", "expression", "식 평가", "sqrt sin log"),
    "core.add":                          ("더하기", "합계", "sum"),
    "core.sub":                          ("빼기", "차이"),
    "core.mul":                          ("곱하기", "곱셈"),
    "core.div":                          ("나누기", "나눗셈"),
    "core.batch":                        ("일괄 계산", "병렬 계산", "여러 건", "bulk"),
    "core.pipeline":                     ("연속 계산", "단계별 계산", "체인", "workflow"),
    "sootool.verify_receipt":            ("영수증 검증", "계산 증빙", "재실행 검증", "receipt"),
    "core.solve_for":                    ("역산", "목표값 찾기", "거꾸로 계산", "goal seek", "inverse"),
    "core.compare":                      ("시나리오 비교", "비교 계산", "what-if", "대안 비교"),
    "core.explain":                      ("계산 설명", "근거 설명", "계산 과정", "explain", "평문 풀이"),
    "payroll.kr_gross_from_net":         ("세후에서 세전", "연봉 역산", "세전 월급 구하기", "실수령액으로 월급 역산", "gross up"),
    # 도메인별 추가 별칭
    "accounting.dupont_3":                   ("듀퐁", "듀퐁 분석", "자기자본이익률 분해", "return on equity breakdown"),
    "accounting.dupont_5":                   ("듀퐁", "확장 듀퐁 분석", "세부담 이자부담 분해", "five-step breakdown"),
    "crypto.carmichael_lambda":              ("카마이클 함수", "RSA 지수", "reduced totient"),
    "crypto.crt":                            ("연립 나머지 방정식", "chinese remainder theorem"),
    "crypto.egcd":                           ("베주 계수", "extended euclidean", "bezout"),
    "crypto.euler_totient":                  ("오일러 파이 함수", "서로소 개수", "euler phi", "coprime count"),
    "crypto.gcd":                            ("유클리드 호제법", "greatest common divisor"),
    "crypto.hash":                           ("체크섬", "지문", "checksum", "digest"),
    "crypto.is_prime":                       ("소수인지 확인", "밀러라빈", "prime number", "primality test"),
    "crypto.lcm":                            ("분모 맞추기", "least common multiple"),
    "crypto.modinv":                         ("곱셈 역원", "mod 나눗셈", "modular inverse", "multiplicative inverse"),
    "crypto.modpow":                         ("거듭제곱 나머지", "나머지 연산", "modular exponentiation", "powmod"),
    "datetime.fiscal_quarter":               ("분기 구간", "사분기", "Q1 Q2 Q3 Q4", "financial quarter"),
    "datetime.fiscal_year":                  ("결산기", "연도 시작일", "FY", "financial year"),
    "engineering.ac_impedance":              ("교류 임피던스", "리액턴스", "reactance", "RLC impedance"),
    "engineering.beam_deflection":           ("보 처짐", "캔틸레버 보", "단순보", "deflection of beam"),
    "engineering.bearing_equivalent_load":   ("베어링 하중 합성", "radial axial combined load"),
    "engineering.bearing_life_l10":          ("베어링 수명 계산", "bearing lifetime", "ISO 281"),
    "engineering.bending_stress":            ("굽힘 응력", "굽힘응력", "flexural stress", "beam stress"),
    "engineering.bernoulli":                 ("유체 에너지 보존", "압력 수두", "fluid energy conservation"),
    "engineering.bode_magnitude_phase":      ("보드 선도", "주파수 응답", "frequency response", "bode plot"),
    "engineering.capacitor_combine":         ("콘덴서", "축전기", "capacitance series parallel"),
    "engineering.convective_heat_transfer":  ("열전달계수", "냉각 열량", "convection", "Newton's law of cooling"),
    "engineering.darcy_weisbach":            ("배관 압력손실", "관 마찰손실", "pipe pressure drop", "friction head loss"),
    "engineering.db_convert":                ("데시벨", "dBm 변환", "decibel", "neper"),
    "engineering.elastic_modulus_relate":    ("탄성계수 관계", "포아송비", "Young's modulus", "shear modulus", "bulk modulus"),
    "engineering.electrical_ohm":            ("옴 법칙", "전압 전류 저항", "ohms law"),
    "engineering.electrical_power":          ("전력 계산", "소비전력", "와트", "power dissipation"),
    "engineering.euler_buckling":            ("압축 부재 좌굴", "column buckling", "critical buckling load"),
    "engineering.exponential_reliability":   ("고장률 신뢰도", "평균 수명", "failure rate", "exponential distribution"),
    "engineering.first_order_response":      ("1차 지연", "1차 지연 시스템", "first order lag", "time response"),
    "engineering.fluid_reynolds":            ("유체 흐름 판별", "관 유동 상태", "flow regime"),
    "engineering.fourier_heat_conduction":   ("벽 열손실", "단열재 열전달", "conduction heat loss", "heat flux through wall"),
    "engineering.gear_ratio":                ("기어 감속비", "변속비", "gear reduction ratio", "speed ratio"),
    "engineering.gear_torque_transmission":  ("기어 출력 토크", "감속기 토크", "gearbox output torque"),
    "engineering.hardness_convert":          ("경도 변환", "로크웰 비커스 브리넬", "Rockwell Vickers Brinell"),
    "engineering.hazen_williams_flow":       ("배관 유량", "상수도 관로 유량", "water pipe flow rate"),
    "engineering.inductor_combine":          ("코일", "인덕턴스 합성", "inductance series parallel"),
    "engineering.lc_resonant_frequency":     ("공진 회로", "resonance frequency", "tank circuit"),
    "engineering.lmtd":                      ("평균 온도차", "log mean temperature difference", "heat exchanger"),
    "engineering.max_power_transfer":        ("임피던스 매칭", "최대 전력 전송", "impedance matching", "load matching"),
    "engineering.mech_strain":               ("늘어난 비율", "변형량 비율", "engineering strain"),
    "engineering.mech_stress":               ("응력 계산", "단위 면적당 힘", "axial stress"),
    "engineering.moment_of_inertia":         ("관성 모멘트", "회전 관성", "rotational inertia"),
    "engineering.moody_friction_factor":     ("무디 선도", "배관 조도", "colebrook equation", "pipe roughness"),
    "engineering.norton_equivalent":         ("노튼", "노튼 등가", "norton theorem"),
    "engineering.opamp_gain":                ("연산증폭기", "오피앰프", "op amp", "operational amplifier"),
    "engineering.parallel_reliability":      ("이중화 신뢰도", "중복 설계", "redundancy", "redundant system"),
    "engineering.pid_discrete_output":       ("PID 제어", "피아이디", "디지털 PID", "PID controller"),
    "engineering.power_factor_correction":   ("역률 개선", "진상 콘덴서", "power factor correction"),
    "engineering.pump_hydraulic_power":      ("펌프 동력", "펌프 소요 동력", "pump power", "water horsepower"),
    "engineering.rc_filter_cutoff":          ("컷오프 주파수", "저역통과 필터", "고역통과 필터", "cutoff frequency"),
    "engineering.resistor_color_code":       ("저항 색띠", "저항 컬러", "color bands", "resistor bands"),
    "engineering.resistor_parallel":         ("저항 병렬", "병렬 저항", "parallel resistance"),
    "engineering.resistor_series":           ("저항 직렬", "직렬 저항", "series resistance"),
    "engineering.rlc_time_constant":         ("시상수", "RC 시상수", "time constant", "damping"),
    "engineering.safety_factor":             ("안전계수", "안전 여유", "factor of safety", "FOS"),
    "engineering.second_order_response":     ("감쇠비", "2차 지연 시스템", "second order system", "damping ratio"),
    "engineering.section_moment_inertia":    ("단면 2차 모멘트", "단면2차모멘트", "area moment of inertia", "second moment of area"),
    "engineering.series_reliability":        ("직렬 구조 신뢰도", "직렬 연결 고장", "system reliability", "series system"),
    "engineering.shear_stress":              ("전단 응력", "beam shear", "transverse shear"),
    "engineering.si_prefix_convert":         ("접두어 변환", "킬로 메가 기가", "metric prefix", "unit prefix"),
    "engineering.sn_fatigue_life":           ("피로 수명", "S-N 곡선", "Basquin equation"),
    "engineering.stefan_boltzmann":          ("복사열", "방사", "radiant heat", "thermal radiation"),
    "engineering.thermal_expansion_strain":  ("열팽창", "온도에 따른 길이 변화", "CTE", "linear expansion"),
    "engineering.thermal_resistance":        ("열저항 합성", "열 회로", "thermal circuit", "R-value"),
    "engineering.thevenin_equivalent":       ("테브닌", "테베닌", "thevenin theorem"),
    "engineering.three_phase_power":         ("삼상 전력", "3상 전력", "three phase power"),
    "engineering.torque_rotational_power":   ("모터 출력", "토크 회전수 출력", "shaft power", "motor power"),
    "engineering.weibull_reliability":       ("수명 분포", "고장 확률", "life distribution", "failure probability"),
    "finance.bond_duration":                 ("듀레이션", "금리 민감도", "채권 금리 위험", "interest rate sensitivity", "macaulay"),
    "finance.forward_price":                 ("선도 가격", "선도계약", "선도 이론가", "forward contract"),
    "finance.futures_price":                 ("선물 이론가", "보유비용 모형", "cost of carry", "futures fair value"),
    "finance.option_payoff":                 ("옵션 손익", "만기 손익", "배리어 옵션", "knock-out option", "exotic option"),
    "finance.sortino_ratio":                 ("소르티노", "하방 위험 수익률", "downside risk ratio"),
    "finance.var_parametric":                ("위험가치", "정규분포 VaR", "분산공분산 VaR", "expected shortfall", "value at risk"),
    "geometry.area_circle":                  ("원 면적", "circle area", "원의 크기"),
    "geometry.area_polygon":                 ("땅 면적 좌표", "토지 면적", "좌표로 면적", "surveyor formula"),
    "geometry.area_rectangle":               ("사각형 면적", "가로 세로 면적", "rectangle surface"),
    "geometry.area_triangle":                ("삼각형 면적", "triangle surface"),
    "geometry.haversine":                    ("두 지점 거리", "위도 경도 거리", "GPS 거리", "great circle distance"),
    "geometry.matrix_determinant":           ("det", "특이행렬 판별", "invertible check"),
    "geometry.matrix_inverse":               ("inv", "matrix inversion", "행렬 뒤집기"),
    "geometry.matrix_multiply":              ("행렬곱", "matrix product", "mat mul"),
    "geometry.matrix_solve":                 ("연립방정식", "linear system", "Ax=b"),
    "geometry.vector_cross":                 ("벡터곱", "cross product", "법선 벡터"),
    "geometry.vector_dot":                   ("내적 계산", "scalar product", "inner product"),
    "geometry.vector_norm":                  ("벡터 크기", "벡터 길이", "magnitude", "euclidean length", "L2 norm"),
    "geometry.volume_cuboid":                ("상자 부피", "박스 부피", "box volume", "rectangular prism"),
    "geometry.volume_cylinder":              ("원통 부피", "캔 용량", "tank volume"),
    "geometry.volume_sphere":                ("구 체적", "공 부피", "ball volume"),
    "math.diff_central":                     ("수치 미분", "기울기", "변화율", "numerical derivative", "finite difference"),
    "math.diff_five_point":                  ("수치 미분", "고정밀 미분", "numerical derivative", "stencil"),
    "math.fft":                              ("주파수 분석", "스펙트럼", "fast fourier transform", "spectrum"),
    "math.ifft":                             ("역푸리에", "신호 복원", "inverse fourier transform", "time domain"),
    "math.integrate_gauss_legendre":         ("적분 계산", "수치 적분", "quadrature", "numerical integration"),
    "math.integrate_simpson":                ("적분 계산", "수치 적분", "definite integral", "numerical integration", "area under curve"),
    "math.interpolate_cubic_spline":         ("곡선 보간", "부드러운 곡선", "smooth curve", "natural spline"),
    "math.interpolate_linear":               ("사이 값", "표 값 추정", "lerp", "np.interp"),
    "math.polynomial_horner":                ("다항식 값", "다항식 계산", "evaluate polynomial", "polyval"),
    "math.polynomial_roots":                 ("방정식의 근", "n차 방정식", "이차방정식", "quadratic formula", "find roots", "zeros of polynomial"),
    "medical.cha2ds2_vasc":                  ("항응고제 적응", "차즈 점수", "atrial fibrillation stroke risk"),
    "medical.dose_weight_based":             ("약물 용량", "체중당 용량", "weight-based dosing"),
    "medical.framingham_cvd_10y":            ("심장병 발병 확률", "heart attack risk", "10-year CVD risk"),
    "medical.has_bled":                      ("와파린 출혈 점수", "anticoagulant bleeding risk"),
    "medical.qtc_bazett":                    ("심전도 간격 보정", "ECG QT correction"),
    "medical.qtc_framingham":                ("심전도 간격 보정", "ECG QT correction"),
    "medical.qtc_fridericia":                ("심전도 간격 보정", "ECG QT correction"),
    "medical.qtc_hodges":                    ("심전도 간격 보정", "ECG QT correction"),
    "pm.earned_schedule":                    ("일정 지연 예측", "ES 기법", "time-based SPI"),
    "probability.bayes":                     ("사후확률", "조건부확률", "posterior probability"),
    "probability.beta_cdf":                  ("베타 분포", "누적확률", "beta cumulative"),
    "probability.beta_pdf":                  ("베타 분포", "확률밀도", "beta density"),
    "probability.beta_ppf":                  ("베타 분포", "분위수", "inverse beta"),
    "probability.binomial_cdf":              ("이항 누적", "k회 이하", "binomial cumulative"),
    "probability.binomial_pmf":              ("이항 확률", "n번 중 k번", "binomial probability"),
    "probability.chi_square_cdf":            ("카이 제곱", "p값", "chi2 cdf"),
    "probability.chi_square_pdf":            ("카이 제곱", "chi2", "chi-squared density"),
    "probability.chi_square_ppf":            ("카이 제곱", "임계값", "chi2 critical value"),
    "probability.expected_value":            ("기대값", "평균값", "expectation"),
    "probability.exponential_cdf":           ("지수 분포", "고장 확률", "exponential cumulative"),
    "probability.exponential_pdf":           ("지수 분포", "확률밀도", "exponential density"),
    "probability.exponential_ppf":           ("지수 분포", "분위수", "inverse exponential"),
    "probability.f_cdf":                     ("F 분포", "p값", "f distribution cumulative"),
    "probability.f_pdf":                     ("F 분포", "확률밀도", "fisher snedecor"),
    "probability.f_ppf":                     ("F 분포", "임계값", "f critical value"),
    "probability.factorial":                 ("팩토리얼", "계승"),
    "probability.gamma_cdf":                 ("감마 분포", "누적확률", "gamma cumulative"),
    "probability.gamma_pdf":                 ("감마 분포", "확률밀도", "gamma density"),
    "probability.gamma_ppf":                 ("감마 분포", "분위수", "inverse gamma"),
    "probability.lognormal_cdf":             ("로그 정규", "누적확률", "lognormal cumulative"),
    "probability.lognormal_pdf":             ("로그 정규", "확률밀도", "lognormal density"),
    "probability.lognormal_ppf":             ("로그 정규", "분위수", "inverse lognormal"),
    "probability.nCr":                       ("조합", "경우의 수", "combination", "choose"),
    "probability.nPr":                       ("순열", "경우의 수", "permutation"),
    "probability.normal_cdf":                ("누적확률", "z-score", "표준정규분포", "gaussian cdf"),
    "probability.normal_pdf":                ("가우스 분포", "확률밀도", "gaussian", "bell curve"),
    "probability.normal_ppf":                ("분위수", "z 값", "inverse normal", "norm.ppf"),
    "probability.poisson_cdf":               ("푸아송", "발생 횟수 누적", "poisson cumulative"),
    "probability.poisson_pmf":               ("푸아송", "발생 횟수 확률", "poisson probability"),
    "science.battery_capacity":              ("전지 용량 환산", "Ah Wh conversion"),
    "science.bragg":                         ("X선 회절", "결정 격자", "X-ray diffraction"),
    "science.faraday_electrolysis":          ("도금 석출량", "패러데이 법칙", "electroplating mass"),
    "science.half_life":                     ("반감기", "붕괴 잔량", "radioactive decay"),
    "science.ideal_gas":                     ("이상기체 상태방정식", "gas law"),
    "science.intensity":                     ("전력 밀도", "irradiance", "power density"),
    "science.molar_mass":                    ("분자량", "화학식 질량", "molecular weight"),
    "science.nernst":                        ("네른스트", "전지 전압", "cell potential"),
    "science.snell_law":                     ("굴절 법칙", "refraction angle"),
    "science.stoichiometry":                 ("화학양론", "한계 시약", "limiting reagent"),
    "science.thin_lens":                     ("렌즈 공식", "상 위치", "lens equation", "focal length"),
    "stats.cohens_d":                        ("코헨 d", "표준화 평균차", "effect size"),
    "stats.eta_squared":                     ("에타 제곱", "분산 설명 비율", "omega squared"),
    "stats.kruskal_wallis":                  ("크루스칼 왈리스", "비모수 분산분석", "nonparametric ANOVA"),
    "stats.wilcoxon":                        ("윌콕슨", "비모수 대응 검정", "signed-rank"),
    "symbolic.diff":                         ("미분", "변화율", "derivative", "differentiate", "calculus"),
    "symbolic.solve":                        ("방정식 풀이", "해 구하기", "x 구하기", "equation solver", "solve for x", "algebra"),
    "units.data_size_convert":               ("용량 변환", "바이트", "저장 용량", "bytes", "file size"),
    "units.energy_convert":                  ("열량", "칼로리", "줄", "calorie", "joule"),
    "units.pressure_convert":                ("기압", "공기압", "혈압 단위", "atmospheric pressure"),
    "units.time_small_convert":              ("밀리초", "나노초", "초 시간 변환", "milliseconds", "nanoseconds"),
    # 신규 도구와 추가 별칭
    "core.pipeline_resume": ("실패 단계 재실행", "이어서 실행", "restart pipeline", "retry from step"),
    "payroll.kr_health_income_premium": ("소득월액보험료", "보수외소득 건강보험료", "건강보험료 정산", "4월 건강보험 정산", "health insurance income premium"),
    "payroll.kr_minimum_wage_check": ("최저임금", "최저시급", "최저임금 위반", "최저임금 산입범위", "minimum wage"),
    "payroll.kr_national_pension_benefit": ("국민연금 수령액", "노령연금", "예상연금", "조기노령연금", "연기연금", "national pension benefit"),
    "payroll.kr_overtime_pay": ("연장근로수당", "야근수당", "야간수당", "휴일근로수당", "가산임금", "통상시급", "overtime pay"),
    "payroll.kr_weekly_holiday_pay": ("주휴수당", "주휴", "알바 주휴수당", "weekly holiday pay"),
    "realestate.kr_subscription_score": ("청약 가점 계산", "housing subscription point score"),
    "sootool.policy_activate": ("초안 승인", "정책 적용", "publish", "approve draft"),
    "sootool.policy_diff": ("연도별 세율 차이", "개정 전후", "year over year", "what changed"),
    "sootool.policy_export": ("내보내기", "백업", "정책 이식", "backup", "download policy"),
    "sootool.policy_get": ("세율표 조회", "기준값 조회", "세율 구간 보기", "rate table lookup"),
    "sootool.policy_history": ("개정 이력", "변경 이력", "audit log", "changelog"),
    "sootool.policy_import": ("가져오기", "정책 복원", "restore", "upload policy"),
    "sootool.policy_list": ("세율표 목록", "법령 기준값 목록", "rate tables", "available tables"),
    "sootool.policy_propose": ("세율 개정 제안", "새 세율표 등록", "draft", "amend rates"),
    "sootool.policy_rollback": ("개정 취소", "원복", "revert", "undo"),
    "sootool.policy_validate": ("정책 yaml 점검", "해시 확인", "schema check", "lint"),
    "sootool.skill_guide": ("사용법", "도구 안내", "도움말", "how to use", "help"),
    "tax.kr_eitc": ("근로장려금", "earned income tax credit"),
    "tax.kr_pension_income": ("연금소득세", "연금저축 인출 세금", "IRP 연금 수령 세금", "연금소득공제", "pension income tax"),
    "tax.kr_registration_license_tax": ("등록면허세 계산", "registration license tax"),
    "tax.kr_securities_transaction": ("증권거래세", "주식 매도 세금", "거래세", "농특세 주식", "securities transaction tax"),
    "tax.kr_vehicle_tax": ("자동차세 계산", "korea automobile tax"),
    "tax_us.fica": ("미국 급여세", "미국 사회보장세", "메디케어세", "자영업세", "FICA", "payroll tax", "self-employment tax", "medicare tax"),
    "tax.kr_comprehensive_income_tax": ("종합소득세 신고 계산", "금융소득 종합과세", "배당세액공제", "5월 종소세", "comprehensive income tax return"),
}
